#!/bin/bash
# Start/stop the iptables script.
#
### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Custom background script
# Description:       iptables v1.4.2 for Squeeze
#                    Last Update:2012/08/13
#                    Author     :labunix@linux.jp
#                    IPv4 only
### END INIT INFO
#
# environment
#export PATH=/sbin:/usr/sbin:/bin:/usr/bin
set -e

function sfwflush() {
  echo $@
  iptables -F
  iptables -F -t nat
  iptables -X
  iptables -P INPUT ACCEPT
  iptables -P FORWARD ACCEPT
  iptables -P OUTPUT ACCEPT
}

# for save and restore
test -f /etc/iptables-save || touch /etc/iptables-save
case $1 in
start)
  iptables-restore -c /etc/iptables-save
  exit 0
  ;;
stop)
  echo "backup to /etc/iptables-save.bak"
  cat /etc/iptables-save > /etc/iptables-save.bak
  iptables-save -c > /etc/iptables-save
  sfwflush "Stop iptables..."
  exit 0
  ;;
reload|restart)
  echo "backup /etc/iptables-save"
  cat /etc/iptables-save > /etc/iptables-save.bak
  iptables-save -c > /etc/iptables-save
  sfwflush "Stop iptables..."
  iptables-restore -c /etc/iptables-save
  exit 0
  ;;
reconfigure)
  echo "backup Runnig iptables"
  iptables-save -c > /etc/iptables-save.bak
  sfwflush "Stop iptables..."
  iptables-restore -c /etc/iptables-save
  exit 0
  exit 0
  ;;
*)
  echo "Usage: $0 {start|stop|reload|reconfigure|restart}"
  echo "[reload]      save Running iptables."
  echo "[reconfigure] save /etc/iptables-save."
  exit 1
  ;;
esac
exit 0

