#!/bin/bash
### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Custom script for iptables
# Description:       Custom script for iptables (Squeeze)
#                    Last Update:2012/11/10
#                    Author     :labunix@linux.jp
### END INIT INFO

function myreset() {
  echo -n "$@"
  if [ -s "${MYSAVE}" ];then
    mv "$MYSAVE" "$MYBACK" && echo -ne "\nSave...\n $MYBACK\n"
  else
    rm "$MYBACK"
  fi
  iptables-save -c > "${MYSAVE}"

  # delete filter rules
  for MYFILTER in INPUT OUTPUT FORWARD;do
    iptables -t filter -F "$MYFILTER"
  done
  iptables -t filter -F
  unset MYFILTER

  # delete mangle rules
  for MYMANGLE in PREROUTING POSTROUTING INPUT OUTPUT FORWARD;do
    iptables -t mangle -F "$MYMANGLE"
  done
  iptables -t mangle -F
  unset MYMANGLE

  # delete nat rules
  for MYNAT in PREROUTING POSTROUTING OUTPUT;do
    iptables -t nat -F "$MYNAT"
  done
  iptables -t nat -F
  unset MYNAT

  # delete raw rules
  for MYRAW in PREROUTING OUTPUT;do
    iptables -t raw -F "$MYRAW"
  done
  iptables -t raw -F
  unset MYRAW

  # delete policy rules
  for MYPOLICY in INPUT OUTPUT FORWARD;do
    iptables -P "$MYPOLICY" ACCEPT
  done
  unset MYPOLICY

  # delete custom chain
  iptables -L | grep Chain | grep -v "INPUT\|OUTPUT\|FORWARD" | \
  for MYCHAIN in `xargs`;do
    iptables -X "$MYCHAIN"
  done
  unset MYCHAIN

  # argument check
  if [ "$1" == "ERROR" ];then
    exit 1
  fi

  # ending
  unset MYUNIXTIME MYSAVE MYBACK
  echo "done"
  exit 0
}

# save file and backup file
MYUNIXTIME=`date '+%s'`
MYSAVE="/etc/iptables-save"
MYBACK="${MYSAVE}.${MYUNIXTIME}"
test -f "$MYSAVE" || touch "$MYSAVE"
test -f "$MYSAVE" || myreset "ERROR : touch $MYSAVE"
test -f "$MYBACK" || touch "$MYBACK"
test -f "$MYBACK" || myreset "ERROR : touch $MYBACK"

if [ "`id -u`" -ne "0" ];then
  myreset "ERROR : Sorry, Not Permit User!"
fi

chmod 600 "$MYSAVE" || myreset "ERROR : chmod $MYSAVE"
chmod 600 "$MYBACK" || myreset "ERROR : chmod $MYBACK"

case $1 in
start)
  echo -n "$0 starting... "
  iptables-restore -c "$MYSAVE" || myreset "ERROR : iptables not start!"
  echo "done"
  ;;
stop)
  myreset "$0 stopping... "
  ;;
*)
  echo "Usege $0 [start|stop]"
  ;;
esac

# ending for Usage
unset MYUNIXTIME MYSAVE MYBACK
exit 0
