#!/bin/bash

if [ `id -u` -ne "0" ] ;then
  echo "Sorry,Not Permit User"
  exit 1
fi

SRCLOG=/var/log/iptables.log
#SRCLOG=/var/log/syslog
#SRCLOG=/var/log/messages
#SRCLOG=/var/adm/messages

SFWTEMP=/var/log/sfwreport.tmp
SFWLOG=/var/log/sfwreport.log

grep "IN=" ${SRCLOG} | \
  sed s/".*IN="/"IN="/g | \
  sed s/"LEN=[0-9]* \|TOS=0x[0-9A-Fa-f]* \|PREC=0x[0-9A-Fa-f]* "//g | \
  sed s/"TTL=[0-9]* \|DF \|WINDOW=[0-9]* \|ACK \|PSH \|URGP=[0-9]* "//g | \
  sed s/"RES=0x[0-9]* \|SYN \|ID=[0-9]* "//g | \
  sed s/" MAC=..:..:..:..:..:..:..:..:..:..:..:..:..:.. "//g > ${SFWTEMP}

cat ${SFWTEMP} | sed s/"IN= \|OUT= "//g | \
  sed s/"IN="/'-i '/g | \
  sed s/"OUT="/'-o '/g | \
  sed s/"SRC="/'-s '/g | \
  sed s/"DST="/'-d '/g | \
  sed s/"PROTO="/'-p '/g | \
  sed s/"SPT="/'--sport '/g | \
  sed s/"DPT="/'--dport '/g | \
  sed s/^/"iptables "/g > ${SFWLOG}
exit 0
